### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by chrsjhnsn** [Srinivas11789/PcapXray#14]
```
Traceback (most recent call last):
  File "Source/main.py", line 12, in <module>
    import userInterface
ImportError: No module named userInterface
```

I get this error on macOS 10.13.5, running Python 2.7.15. This error occurs after running `pip install -r requirements.txt`.

Looks like a very cool project, hoping there's an easy package to install that makes it mac compatible, but I'm not seeing anything by googling around.

**Comment by chrsjhnsn** [comment]
Needed to move to the /source directory, couldn't run the script from the pcapxray with `python source/main.py`.

**Comment by Srinivas11789** [comment]
@chrsjhnsn Thanks for using pcapXray, glad you got it resolved. Pull request #8 contains this fix. I would merge it soon.

**Comment by chrsjhnsn** [comment]
@Srinivas11789 thanks! I actually ran into a different show-stopping error right after this. about to open a new issue since it's not related.
