### ISSUE TITLE
Improve Readme.md file

### ISSUE THREAD

**Issue by WinXprt** [Srinivas11789/PcapXray#3]
Can you improvize the Readme.md file with End to End steps on how to use this tool?

**Comment by WinXprt** [comment]
Like after installing all the dependencies

We need to PcapXray->Source

In Source folder we have main.py

Need to run the following command:
python main.py 

Then will get the GUI interface where will give our .pcap file and select the traffic which we want to analyse and then Click on "Analyse" for more information about the network traffic present in the pcap file.

**Comment by Srinivas11789** [comment]
Updated readme with some instructions and a demo
